import { defineTerms } from "./types";

// Deliberately excluded: ambiguous names that are also everyday words or
// single letters ("Go", "R", "C", "Swift", "Spring", "Express", "REST") —
// they're listed only in unambiguous forms to avoid false matches.

export const PROGRAMMING_TERMS = defineTerms("programming", [
  ["javascript", "JavaScript", ["js", "ecmascript", "es6", "جافا سكريبت", "جافاسكريبت"]],
  ["typescript", "TypeScript", ["ts", "تايب سكريبت"]],
  ["python", "Python", ["بايثون"]],
  ["java", "Java", ["جافا"]],
  ["csharp", "C#", ["c sharp", "csharp"]],
  ["cpp", "C++", ["cpp"]],
  ["php", "PHP", []],
  ["ruby", "Ruby", []],
  ["golang", "Go (Golang)", ["golang"]],
  ["kotlin", "Kotlin", []],
  ["swift-lang", "Swift (iOS)", ["swift programming", "swiftui"]],
  ["dart", "Dart", []],
  ["rust", "Rust", []],
  ["sql", "SQL", ["t sql", "pl sql"]],
  ["html", "HTML", ["html5"]],
  ["css", "CSS", ["css3"]],
  ["bash", "Bash", ["shell scripting"]],
]);

export const FRAMEWORK_TERMS = defineTerms("frameworks", [
  ["react", "React", ["react js", "reactjs", "رياكت"]],
  ["nextjs", "Next.js", ["nextjs"]],
  ["vue", "Vue.js", ["vue", "vuejs"]],
  ["nuxt", "Nuxt", ["nuxtjs"]],
  ["angular", "Angular", ["angularjs"]],
  ["svelte", "Svelte", ["sveltekit"]],
  ["react-native", "React Native", []],
  ["flutter", "Flutter", ["فلاتر"]],
  ["nodejs", "Node.js", ["node js", "nodejs"]],
  ["expressjs", "Express.js", ["expressjs"]],
  ["nestjs", "NestJS", ["nest js"]],
  ["django", "Django", []],
  ["flask", "Flask", []],
  ["fastapi", "FastAPI", []],
  ["laravel", "Laravel", ["لارافيل"]],
  ["spring-boot", "Spring Boot", ["spring framework"]],
  ["dotnet", "ASP.NET", ["dotnet", "net core"]],
  ["redux", "Redux", ["redux toolkit"]],
  ["mobx", "MobX", []],
  ["zustand", "Zustand", []],
  ["react-query", "React Query", ["tanstack query"]],
  ["state-management", "State Management", ["state management libraries", "إدارة الحالة"]],
  ["tailwind", "Tailwind CSS", ["tailwind", "tailwindcss"]],
  ["bootstrap", "Bootstrap", []],
  ["sass", "Sass", ["scss"]],
  ["graphql", "GraphQL", []],
  ["rest-api", "RESTful APIs", ["restful", "rest api", "restful api", "restful services"]],
  ["api", "APIs", ["api", "واجهات برمجة التطبيقات"]],
  ["jest", "Jest", []],
  ["cypress", "Cypress", []],
  ["playwright", "Playwright", []],
  ["testing-library", "Testing Library", ["react testing library"]],
  ["unit-testing", "Unit Testing", ["unit tests", "الاختبارات الآلية"]],
]);

export const DATA_TERMS = defineTerms("data", [
  ["postgresql", "PostgreSQL", ["postgres"]],
  ["mysql", "MySQL", []],
  ["mongodb", "MongoDB", ["mongo"]],
  ["redis", "Redis", []],
  ["nosql", "NoSQL", []],
  ["elasticsearch", "Elasticsearch", []],
  ["data-analysis", "Data Analysis", ["data analytics", "تحليل البيانات"]],
  ["machine-learning", "Machine Learning", ["ml", "التعلم الآلي", "تعلم الآلة"]],
  ["ai", "Artificial Intelligence", ["ai", "الذكاء الاصطناعي"]],
  ["deep-learning", "Deep Learning", ["التعلم العميق"]],
  ["pandas", "Pandas", []],
  ["numpy", "NumPy", []],
  ["tensorflow", "TensorFlow", []],
  ["pytorch", "PyTorch", []],
  ["power-bi", "Power BI", ["powerbi"]],
  ["tableau", "Tableau", []],
  ["etl", "ETL", []],
  ["big-data", "Big Data", ["البيانات الضخمة"]],
]);

export const CLOUD_DEVOPS_TERMS = defineTerms("cloudDevops", [
  ["aws", "AWS", ["amazon web services"]],
  ["azure", "Microsoft Azure", ["azure"]],
  ["gcp", "Google Cloud", ["gcp", "google cloud platform"]],
  ["docker", "Docker", []],
  ["kubernetes", "Kubernetes", ["k8s"]],
  ["ci-cd", "CI/CD", ["ci cd", "continuous integration", "continuous deployment"]],
  ["github-actions", "GitHub Actions", []],
  ["terraform", "Terraform", []],
  ["linux", "Linux", ["لينكس"]],
  ["microservices", "Microservices", ["microservice architecture"]],
  ["serverless", "Serverless", []],
  ["cybersecurity", "Cybersecurity", ["cyber security", "information security", "الأمن السيبراني"]],
  ["networking", "Networking", ["computer networks", "الشبكات"]],
]);
